use_frameworks!

target 'NVNLocales_Example' do
  pod 'NVNLocales', :path => '../'

  target 'NVNLocales_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
